--[[
  This file is used to set keymaps for Neovim.
  It uses the 'keymaps' module to set keymaps in a more readable way.
  A keymaps list contains one or many list tables with 4 table items { mode, lhs, rhs, desc }
--]]
require('keymaps').set({
  --  in normal mode: Navigate widows with ctrl + arrow keys
  { 'n', '<C-Down>',   '<CMD>wincmd j<CR>', 'Move to lower window' },
  { 'n', '<C-Up>',     '<CMR>wincmd k<CR>', 'Move to upper window' },
  { 'n', '<C-Left>',   '<CMD>wincmd h<CR>', 'Move to left window' },
  { 'n', '<C-Right>',  '<CMD>wincmd l<CR>', 'Move to right window' },
  -- double  escape to exit terminal mode
  { 't', '<esc><esc>', '<C-\\><C-n>',       'Exit terminal mode' },
})




--[[
 if we have created a command
  the rhs will be '<cmd>CommandName<NL>'
  and we pass the CommandName as the 3 param
  The description will be generated by breaking down the command name into words
--]] --





--[[
--
 if we provide a command like string e.g. "RepoIssueView"
  the passed in keymaps table will have 3 list items { mode, lhs, "RepoIssueView" }
  The description will be generated by breaking down the command name into words
  The set keymap rhs will be the resolved function
--]] --
