# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.0"
"rocks-git.nvim" = "2.5.2"

"conform.nvim" = "8.3.0"
"flash.nvim" = "2.1.0"
"fzf-lua" = "0.0.1605"
"gitsigns.nvim" = "0.9.0"
"mini.align" = "0.14.0"
"mini.bufremove" = "0.14.0"
"mini.clue" = "0.14.0"
"mini.cursorword" = "0.14.0"
"mini.icons" = "0.14.0"
"mini.indentscope" = "0.14.0"
"mini.notify" = "0.14.0"
"mini.sessions" = "0.14.0"
"mini.splitjoin" = "0.14.0"
"mini.statusline" = "0.14.0"
"mini.surround" = "0.14.0"
"mini.tabline" = "0.14.0"
"mini.trailspace" = "0.14.0"
"noice.nvim" = "4.9.0"
"oil.nvim" = "2.14.0"
"quicker.nvim" = "1.3.0"
"render-markdown.nvim" = "7.7.0"
"toggleterm.nvim" = "2.13.1"
## tree-sitter parsers
tree-sitter-toml = "0.0.31"
tree-sitter-gleam = "0.0.33"
tree-sitter-jq = "0.0.29"
tree-sitter-make = "0.0.29"
tree-sitter-bash = "0.0.37"
tree-sitter-regex = "0.0.38"
# Dev scm
"kanagawa.nvim" = "scm"
"plenary.nvim" = "scm"
"mini.hipatterns" = "0.14.0"
"mini.completion" = "0.14.0"
"lspkind.nvim" = "scm"

[plugins."copilot.lua" ]
git = "github:zbirenbaum/copilot.lua"
rev = "d3783b9283a7c35940ed8d71549030d5f5f9f980"
branch = "master"

[plugins."CopilotChat.nvim" ]
git = "github:CopilotC-Nvim/CopilotChat.nvim"
rev = "v3.3.3"
branch = "main"
