local M = {}
M.version = "0.1.0"
M.description = [[
 - overview: keymaps module: set keymaps with a table
 - scope: module scope
 - usage: how to use the module
]]

-- A TODO list of tasks to be completed for the module's implementation
M.implementation = [[
 - [ ] todo task 1
 - [ ] todo task 3
]]

M.references = [[
 - reference 1 url to gh issue or discussion
 - reference 2 file path to local documentation
]]

--[[ section: local utils ]]
local util = require('util')

--[[
 each keymap is a table with the format { mode, lhs, rhs, desc }
--]]
---@param keymaps table[] a list of keymap definitions, where each keymap is a table with the format { mode, lhs, rhs, desc }
---@param bufnr integer|nil the buffer number to set the commands for, if nil the commands will be global
---@return nil
M.set = function(keymaps, bufnr)
  if not bufnr then
    for _, keymap in ipairs(keymaps) do
      vim.keymap.set(keymap[1], keymap[2], keymap[3], { desc = keymap[4] })
    end
  else
    for _, keymap in ipairs(keymaps) do
      vim.keymap.set(keymap[1], keymap[2], keymap[3], { buffer = bufnr, desc = keymap[4] })
    end
  end
end

---@param keymaps table[] a list of keymap definitions, where each keymap is a table with the format { mode, lhs, rhs, desc }
---@param bufnr integer|nil the buffer number to set the commands for, if nil the commands will be global
---@return nil
M.set_dynamic = function(keymaps, bufnr)
  if not bufnr then
    for _, keymap in ipairs(keymaps) do
      vim.keymap.set(keymap[1], keymap[2], keymap[3], { desc = keymap[4], expr = true, replace_keycodes = true })
    end
  else
    for _, keymap in ipairs(keymaps) do
      vim.keymap.set(keymap[1], keymap[2], keymap[3],
        { buffer = bufnr, desc = keymap[4], expr = true, replace_keycodes = true })
    end
  end
end

--[[
keymaps list table will have 3 list items { mode, lhs, "ModuleFunctionName" }
if we provide a command like string e.g. "RepoIssueView"
we parse the string using the util funcs to get the description

--]] --

---@param keymaps table[] a list of keymap definitions, where each keymap is a table with the format { mode, lhs, rhs}
---@param bufnr integer|nil the buffer number to set the commands for, if nil the commands will be global
---@return nil
M.setWithComand = function(keymaps, bufnr)
  if not bufnr then
    for _, k in ipairs(keymaps) do
      local description = util.description(util.split_words(k[3])) or ''
      local cmd = '<CMD>' .. k[3] .. '<CR>'
      vim.keymap.set(k[1], k[2], cmd, { desc = description })
    end
  else
    for _, k in ipairs(keymaps) do
      local description = util.description(util.split_words(k[3])) or ''
      local cmd = '<CMD>' .. k[3] .. '<CR>'
      vim.keymap.set(k[1], k[2], cmd, { buffer = bufnr, desc = description })
    end
  end
end





--[[
--
if we provide a command like string e.g. "RepoIssueView"
the passed in keymaps table will have 3 list items { mode, lhs, "RepoIssueView" }
The description will be generated by breaking down the command name into words
The set keymap rhs will be the resolved function
--]] --

M.setWithFunc = function(keymaps, bufnr)
  local get_func_and_desc = util.get_func_and_description
  if not bufnr then
    for _, k in ipairs(keymaps) do
      local func, description = get_func_and_desc(k[3])
      if not func then
        --TODO log a warning that the function was not found for the command
        vim.notify(string.format("User Commands: no function found for command '%s'", description), vim.log.levels.WARN)
      else
        vim.keymap.set(k[1], k[2], function(args) func(args) end, { desc = description })
      end
    end
  end
end


return M
